//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package azcommunicationidentity

// CommunicationIdentityTokenScope - List of scopes for an access token.
type CommunicationIdentityTokenScope string

const (
	CommunicationIdentityTokenScopeChat CommunicationIdentityTokenScope = "chat"
	CommunicationIdentityTokenScopeVoip CommunicationIdentityTokenScope = "voip"
)

// PossibleCommunicationIdentityTokenScopeValues returns the possible values for the CommunicationIdentityTokenScope const type.
func PossibleCommunicationIdentityTokenScopeValues() []CommunicationIdentityTokenScope {
	return []CommunicationIdentityTokenScope{	
		CommunicationIdentityTokenScopeChat,
		CommunicationIdentityTokenScopeVoip,
	}
}

