//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package azcommunicationidentity

// ClientCreateResponse contains the response from method Client.Create.
type ClientCreateResponse struct {
	AccessTokenResult
}

// ClientDeleteResponse contains the response from method Client.Delete.
type ClientDeleteResponse struct {
	// placeholder for future response values
}

// ClientExchangeTeamsUserAccessTokenResponse contains the response from method Client.ExchangeTeamsUserAccessToken.
type ClientExchangeTeamsUserAccessTokenResponse struct {
	AccessToken
}

// ClientIssueAccessTokenResponse contains the response from method Client.IssueAccessToken.
type ClientIssueAccessTokenResponse struct {
	AccessToken
}

// ClientRevokeAccessTokensResponse contains the response from method Client.RevokeAccessTokens.
type ClientRevokeAccessTokensResponse struct {
	// placeholder for future response values
}
