//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package azcommunicationidentity

// ClientCreateUserResponse contains the response from method Client.CreateUser.
type ClientCreateUserResponse struct {
	AccessTokenResult
}

// ClientDeleteUserResponse contains the response from method Client.DeleteUser.
type ClientDeleteUserResponse struct {
	// placeholder for future response values
}

// ClientGetTokenForTeamsUserResponse contains the response from method Client.GetTokenForTeamsUser.
type ClientGetTokenForTeamsUserResponse struct {
	AccessToken
}

// ClientGetTokenResponse contains the response from method Client.GetToken.
type ClientGetTokenResponse struct {
	AccessToken
}

// ClientRevokeTokensResponse contains the response from method Client.RevokeTokens.
type ClientRevokeTokensResponse struct {
	// placeholder for future response values
}

